[package]
name = "energy_trading_program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.18.1"
borsh = "0.10.3"
borsh-derive = "0.10.3"

[lib]
crate-type = ["cdylib", "lib"]


